import React from 'react';
import { useCurrency } from '../../context/CurrencyContext';
import { useAuth } from '../../context/AuthContext';
import { useSettings } from '../../context/SettingsContext';

const DashboardReport = React.forwardRef(({ stats }, ref) => {
    const { user } = useAuth();
    const { formatPrice } = useCurrency();
    const { settings } = useSettings();

    // Default data if stats are missing
    const data = stats || { activeMembers: 0, revenueToday: 0, overallRevenue: 0, expensesToday: 0, totalExpenses: 0 };
    const netProfitToday = (data.revenueToday || 0) - (data.expensesToday || 0);
    const netProfitMonth = (data.monthlyRevenue || 0) - (data.totalExpenses || 0);
    const date = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    const time = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

    return (
        <div ref={ref} className="p-8 bg-white text-black min-h-screen font-sans">
            {/* 1. Header Details */}
            <div className="border-b-2 border-primary mb-8 pb-4 flex justify-between items-end">
                <div>
                    <h1 className="text-4xl font-bold text-primary mb-2">{settings?.name || 'IronAge Gym'}</h1>
                    <h2 className="text-xl font-semibold text-gray-700">Daily Business Snapshot</h2>
                    <p className="text-sm text-gray-500 mt-1">Date: {date}</p>
                </div>
                <div className="text-right">
                    <p className="text-xs text-gray-500">Generated on:</p>
                    <p className="text-sm font-bold text-gray-800">{date} {time}</p>
                    <p className="text-xs text-gray-400 mt-1">Generated by: {user?.name || 'Admin'}</p>
                </div>
            </div>

            {/* 2. Financial Summary */}
            <section className="mb-8">
                <h2 className="text-lg font-bold text-gray-800 uppercase tracking-wider border-b border-gray-200 pb-2 mb-4">
                    Financial Summary
                </h2>
                <div className="grid grid-cols-2 gap-8">
                    {/* Today */}
                    <div className="bg-gray-50 p-4 rounded-xl border border-gray-200">
                        <h3 className="text-sm font-semibold text-gray-500 mb-3">Today's Performance</h3>
                        <div className="space-y-2">
                            <div className="flex justify-between">
                                <span className="text-sm text-gray-600">Revenue</span>
                                <span className="font-bold text-gray-800">{formatPrice(data.revenueToday)}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-sm text-gray-600">Expenses</span>
                                <span className="font-medium text-red-500">-{formatPrice(data.expensesToday)}</span>
                            </div>
                            <div className="border-t border-gray-300 pt-2 flex justify-between mt-2">
                                <span className="font-bold text-gray-700">Net Profit</span>
                                <span className={`font-bold ${netProfitToday >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                                    {formatPrice(netProfitToday)}
                                </span>
                            </div>
                        </div>
                    </div>

                    {/* Monthly */}
                    <div className="bg-gray-50 p-4 rounded-xl border border-gray-200">
                        <h3 className="text-sm font-semibold text-gray-500 mb-3">Monthly Performance</h3>
                        <div className="space-y-2">
                            <div className="flex justify-between">
                                <span className="text-sm text-gray-600">Revenue</span>
                                <span className="font-bold text-gray-800">{formatPrice(data.monthlyRevenue)}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-sm text-gray-600">Expenses</span>
                                <span className="font-medium text-red-500">-{formatPrice(data.totalExpenses)}</span>
                            </div>
                            <div className="border-t border-gray-300 pt-2 flex justify-between mt-2">
                                <span className="font-bold text-gray-700">Net Profit</span>
                                <span className={`font-bold ${netProfitMonth >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                                    {formatPrice(netProfitMonth)}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Expense Breakdown */}
                {data.expenseBreakdown && data.expenseBreakdown.length > 0 && (
                    <div className="mt-6">
                        <h3 className="text-sm font-semibold text-gray-500 mb-3 border-b border-gray-100 pb-1">Expense Breakdown (This Month)</h3>
                        <div className="grid grid-cols-2 gap-x-8 gap-y-2 text-sm">
                            {data.expenseBreakdown.map((item, idx) => (
                                <div key={idx} className="flex justify-between items-center text-gray-700">
                                    <span>{item.category}</span>
                                    <span className="font-medium text-red-500">{formatPrice(item.amount)}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                )}
            </section>

            {/* 3. Operational Alerts */}
            <section className="mb-8">
                <h2 className="text-lg font-bold text-gray-800 uppercase tracking-wider border-b border-gray-200 pb-2 mb-4">
                    Operational Alerts
                </h2>
                <div className="grid grid-cols-2 gap-8">
                    {/* Inventory */}
                    <div>
                        <h3 className="text-sm font-semibold text-gray-500 mb-3 flex items-center gap-2">
                            <span className="material-icons-round text-base">inventory_2</span> Low Stock Items
                        </h3>
                        {data.lowStockItems && data.lowStockItems.length > 0 ? (
                            <table className="w-full text-sm text-left">
                                <thead className="bg-gray-100 text-gray-600">
                                    <tr>
                                        <th className="px-2 py-1 rounded-l">Item</th>
                                        <th className="px-2 py-1 text-right rounded-r">Stock</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {data.lowStockItems.slice(0, 5).map((item, idx) => (
                                        <tr key={idx} className="border-b border-gray-100">
                                            <td className="px-2 py-1.5 text-gray-800">{item.name}</td>
                                            <td className="px-2 py-1.5 text-right font-bold text-red-500">{item.stock}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        ) : (
                            <p className="text-sm text-green-600 italic">No low stock alerts.</p>
                        )}
                    </div>

                    {/* Members */}
                    <div>
                        <h3 className="text-sm font-semibold text-gray-500 mb-3 flex items-center gap-2">
                            <span className="material-icons-round text-base">groups</span> Membership Status
                        </h3>
                        <div className="space-y-2 text-sm">
                            <div className="flex justify-between p-2 bg-blue-50 rounded text-blue-800">
                                <span>Active Members</span>
                                <span className="font-bold">{data.activeMembers}</span>
                            </div>
                            <div className="flex justify-between p-2 bg-yellow-50 rounded text-yellow-800">
                                <span>Expiring Soon (7 Days)</span>
                                <span className="font-bold">{data.expiringSoon}</span>
                            </div>
                            <div className="flex justify-between p-2 bg-red-50 rounded text-red-800">
                                <span>Pending Payments</span>
                                <span className="font-bold">{data.pendingPaymentsCount || 0}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* 4. Recent Activity Log */}
            <section>
                <h2 className="text-lg font-bold text-gray-800 uppercase tracking-wider border-b border-gray-200 pb-2 mb-4">
                    Recent Activity
                </h2>
                {data.recentActivity && data.recentActivity.length > 0 ? (
                    <table className="w-full text-sm text-left">
                        <thead className="bg-gray-100 text-gray-600">
                            <tr>
                                <th className="px-3 py-2 rounded-l">Time</th>
                                <th className="px-3 py-2">Action</th>
                                <th className="px-3 py-2 text-right rounded-r">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            {data.recentActivity.slice(0, 10).map((act, idx) => (
                                <tr key={idx} className="border-b border-gray-100 odd:bg-white even:bg-gray-50">
                                    <td className="px-3 py-2 text-gray-500">
                                        {new Date(act.time).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                                    </td>
                                    <td className="px-3 py-2 text-gray-800">
                                        <span className="font-medium">{act.type}</span> - {act.action}
                                    </td>
                                    <td className="px-3 py-2 text-right font-bold text-gray-800">
                                        {act.amount ? formatPrice(act.amount) : '-'}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                ) : (
                    <p className="text-gray-500 italic text-sm">No recent activity recorded today.</p>
                )}
            </section>

            {/* Footer */}
            <div className="mt-12 text-center text-xs text-gray-400 border-t border-gray-100 pt-4">
                <p>{settings?.name || 'IronAge Gym'} • Generated on {date} at {time}</p>
            </div>
        </div>
    );
});

DashboardReport.displayName = 'DashboardReport';

export default DashboardReport;
