export const PRODUCT_CATEGORIES = {
    SUPPLEMENT: 'SUPPLEMENT',
    DRINK: 'DRINK',
    MERCH: 'MERCH',
    EQUIPMENT: 'EQUIPMENT',
    OTHER: 'OTHER'
};

export const EXPENSE_CATEGORIES = {
    UTILITIES: 'UTILITIES',
    SALARY: 'SALARY',
    SUPPLIES: 'SUPPLIES',
    MAINTENANCE: 'MAINTENANCE',
    RENT: 'RENT',
    INVENTORY: 'INVENTORY', // System generated
    SESSION_MATERIAL: 'SESSION_MATERIAL',
    OTHER: 'OTHER'
};

export const REWARD_CATEGORIES = {
    MERCHANDISE: 'MERCHANDISE',
    SUPPLEMENT: 'SUPPLEMENT',
    APPAREL: 'APPAREL',
    EXPERIENCE: 'EXPERIENCE',
    OTHER: 'OTHER'
};

export const REWARD_ACTION_TYPES = {
    NONE: 'NONE',
    FREE_CLASS: 'FREE_CLASS',
    FREE_SESSION: 'FREE_SESSION',
    DISCOUNT: 'DISCOUNT'
};

export const POS_VIEWS = {
    ...PRODUCT_CATEGORIES,
    MEMBERSHIP: 'MEMBERSHIP',
    TRAINERS: 'TRAINERS',
    PACKAGES: 'PACKAGES'
};
