const { PrismaClient } = require('@prisma/client');
const crypto = require('crypto');

const prisma = new PrismaClient();

// Hash for 'password123' generated by Neon Auth (Better Auth)
// Format: salt:hash
const DEFAULT_PASSWORD_HASH = 'c9253c4e3165b9cb6a03a88babe2fcad:989c6e207fb41167fc725e01706cc8e08af49f0240d6e5637f2f68e9c0958609439889601af3e5fa0631e562e25d73c77f38e5e95dc3b9dc330795657dd17f8c';

async function migrate() {
    console.log("Starting migration to Neon Auth...");

    try {
        // --- CLEANUP (OPTIONAL: Enable to reset test env) ---
        console.log("Cleaning up previous migration data...");
        try {
            await prisma.$executeRaw`DELETE FROM neon_auth.session`;
            await prisma.$executeRaw`DELETE FROM neon_auth.account`;
            await prisma.$executeRaw`DELETE FROM neon_auth.user`;
            console.log("Cleanup complete.");
        } catch (cleanupErr) {
            console.warn("Cleanup warning (might be empty):", cleanupErr.message);
        }
        // ----------------------------------------------------

        // 1. Fetch existing Users
        const users = await prisma.user.findMany();
        console.log(`Found ${users.length} existing Users.`);

        // 2. Fetch existing Members (who have email/password)
        const members = await prisma.member.findMany({
            where: {
                email: { not: null },
                password: { not: null }
            }
        });
        console.log(`Found ${members.length} existing Members with credentials.`);

        const allAccounts = [...users.map(u => ({ ...u, type: 'USER' })), ...members.map(m => ({ ...m, name: `${m.firstName} ${m.lastName}`, type: 'MEMBER' }))];
        let successes = 0;
        let skips = 0;
        let errors = 0;

        for (const account of allAccounts) {
            try {
                const email = account.email.toLowerCase();

                // Check if user exists in neon_auth.user
                const existing = await prisma.$queryRaw`
                    SELECT id FROM neon_auth.user WHERE email = ${email}
                `;

                if (existing.length > 0) {
                    console.log(`Skipping ${email} (already exists)`);
                    skips++;
                    continue;
                }

                // Generate IDs
                const userId = crypto.randomUUID();
                const accountId = crypto.randomUUID();
                const now = new Date();

                // Insert into neon_auth.user
                // CAST ID to ::uuid
                await prisma.$executeRaw`
                    INSERT INTO neon_auth.user (id, name, email, "emailVerified", "createdAt", "updatedAt")
                    VALUES (${userId}::uuid, ${account.name || 'User'}, ${email}, true, ${now}, ${now})
                `;

                // Insert into neon_auth.account
                // CAST IDs to ::uuid
                // USE DEFAULT PASSWORD HASH
                await prisma.$executeRaw`
                    INSERT INTO neon_auth.account (id, "userId", "accountId", "providerId", "password", "createdAt", "updatedAt")
                    VALUES (${accountId}::uuid, ${userId}::uuid, ${userId}, 'credential', ${DEFAULT_PASSWORD_HASH}, ${now}, ${now})
                `;

                console.log(`Migrated ${email} (${account.type})`);
                successes++;

            } catch (err) {
                console.error(`Failed to migrate ${account.email}:`, err);
                // detailed error
                if (err.meta) {
                    console.error("Meta:", err.meta);
                }
                errors++;
            }
        }

        console.log("\nMigration Complete.");
        console.log(`Successes: ${successes}`);
        console.log(`Skips: ${skips}`);
        console.log(`Errors: ${errors}`);

    } catch (e) {
        console.error("Critical error during migration:", e);
    } finally {
        await prisma.$disconnect();
    }
}

migrate();
