ALTER TABLE "Plan"
ADD COLUMN IF NOT EXISTS "guestPassEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "guestPassLimitCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Member"
ADD COLUMN IF NOT EXISTS "guestPassUsedCount" INTEGER NOT NULL DEFAULT 0;
