import React, { forwardRef } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useSettings } from '../../context/SettingsContext';

const ReportLayout = forwardRef(({ title, subtitle, dateRange, children }, ref) => {
    const { user } = useAuth();
    const { settings } = useSettings();

    const generatedDate = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    const generatedTime = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

    return (
        <div className="bg-gray-100 min-h-screen p-8 flex flex-col items-center">
            {/* Print Controls - Hidden when printing */}
            <div className="mb-6 w-[210mm] flex justify-between items-center print:hidden">
                <h1 className="text-xl font-bold text-gray-700">Report Preview</h1>
                <div className="flex gap-4">
                    <button
                        onClick={() => window.close()}
                        className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors"
                    >
                        Close
                    </button>
                    <button
                        onClick={() => window.print()}
                        className="px-6 py-2 bg-primary text-white font-bold rounded-lg hover:bg-orange-600 transition-colors shadow-lg"
                    >
                        Print PDF
                    </button>
                </div>
            </div>

            {/* A4 Container */}
            <div ref={ref} className="bg-white shadow-2xl print:shadow-none w-[210mm] min-h-[297mm] print:w-full print:min-h-0 print:m-0 p-12 text-black font-sans relative">

                {/* 1. Header Details */}
                <div className="border-b-2 border-primary mb-8 pb-4 flex justify-between items-end">
                    <div>
                        <h1 className="text-4xl font-bold text-primary mb-2">{settings?.name || 'IronAge Gym'}</h1>
                        <h2 className="text-xl font-semibold text-gray-700">{title}</h2>
                        {subtitle && <p className="text-sm text-gray-500 mt-1">{subtitle}</p>}
                    </div>
                    <div className="text-right">
                        <p className="text-xs text-gray-500">Generated on:</p>
                        <p className="text-sm font-bold text-gray-800">{generatedDate} at {generatedTime}</p>
                        <p className="text-xs text-gray-400 mt-1">Generated by: {user?.name || 'Admin'}</p>
                    </div>
                </div>

                {/* 2. Main Content */}
                <div className="min-h-[600px]">
                    {children}
                </div>

                {/* 3. Footer */}
                <div className="mt-20 text-center text-xs text-gray-400 border-t border-gray-100 pt-4 print:fixed print:bottom-8 print:left-0 print:w-full">
                    <p>{settings?.name || 'IronAge Gym'} • Generated via FitOS Analytics</p>
                </div>
            </div>

            <style>{`
                @media print {
                    @page { size: A4; margin: 0; }
                    body { background: white; -webkit-print-color-adjust: exact; }
                    .print\\:hidden { display: none !important; }
                }
            `}</style>
        </div>
    );
});

ReportLayout.displayName = 'ReportLayout';

export default ReportLayout;
